apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster2-placement
  namespace: apache-test
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      clusterid: cluster2
  clusterReplicas: 1
